version: "3"

services:
  client:
    image: client
    container_name: client
    stdin_open: true
    ports:
      - '8080:80'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - api
  
  api:
    image: api
    container_name: api
    ports:
      - "4200:4200"
