name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  Build_and_push_docker_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create client .env file
      run: |
        touch client/.env
        echo REACT_APP_GOOGLE_API_KEY=${{ secrets.REACT_APP_GOOGLE_API_KEY }} >> client/.env
        cat client/.env
    - name: Create server .env file
      run: |
        touch server/.env
        echo 'MONGO_URI=${{ secrets.MONGO_URI }}' >> server/.env
        echo 'PROD_MODE=true' >> server/.env
        cat server/.env
    - name: Build Docker images
      run: ./scripts/build.sh
    - name: Push Docker images
      run: ./scripts/deploy.sh
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_ID: ${{ secrets.DOCKER_ID }}
